### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not Present, as of: v.1.0.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [alegen/netclip#1]

**Comment by alegen** [comment]
Added link in the main F-Droid forums. My post can be found [here](https://f-droid.org/forums/topic/netclip/#post-18867).

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by locutis-of-borg-1999** [comment]
B-) 8-)

**Comment by alegen** [comment]
So I assume the link is not correct? If so, then please offer more information on what is wrong and how to correct it.

I googled for other applications which are on F-Droid and saw there are several which point to a CHANGELOG.md file in the repo (i.e. what I am also doing).

**Comment by locutis-of-borg-1999** [comment]
You seem to have used:  https://raw.githubusercontent.com/alegen/netclip/HEAD/CHANGELOG.md

Many, might have used the "Releases" page, but ensuring there's content, and concise "release notes".  i.e.:  https://github.com/alegen/netclip/releases
