### ISSUE TITLE
Crashes/stopped, upon launch/run, every time.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [alegen/netclip#2]
No debug logs/info' available, at this time.  

Uninstalled.

**Comment by alegen** [comment]
There was an issue where I was using a method avaialble only for APIs 23 and above. I fixed it in [this commit](https://github.com/alegen/netclip/commit/5e6e59abd8e11268d438d8277508780b1bc1a4e9).

Please let me know if this was the issue you had.

**Comment by locutis-of-borg-1999** [comment]
Okay, that was for for v.1.0.  I have no spare time, to work with alpha/pre-release, so I await the next release.

**Comment by locutis-of-borg-1999** [comment]
I gave it an instal trial, and it worked.  Thanks.
