### ISSUE TITLE
Uses telnet. :-(  Uninstalled.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [alegen/netclip#3]
https://en.wikipedia.org/wiki/Telnet#Security

I often use public WiFi.  

I have an app' from F-Droid that starts, AND STOPS a SFTP server, on the device, on my command.  I saw no way, in netclip, to stop/end/kill the process.  While it's a bit less convenient to open a transferred file sent, for example, via SFTP, it's far more secure.  

https://en.wikipedia.org/wiki/Secure_Shell

**Comment by alegen** [comment]
Thanks for the link and your concern. I am aware of the fact that telnet sends everything in cleartext and that the AP (at the very least) will see your traffic.

I also know what problems ssh solves and how it does that.

Of course, there are plans for future improvements and adding tls support is one of them. I wanted to have a working prototype as soon as possible and not linger forever until I publish something.

For the time being though, the speed that I work at has additional constraints (e.g. my job).

**Comment by locutis-of-borg-1999** [comment]
That's  understandable.  

Many dev's have other responsibilities, and unresolved issues remain open, deferred.  

For the other two issues, you took action, so marking them "closed" was appropriate.
